FROM ubuntu:16.04

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list

# Setup required packages for runner and OpenWRT compilation
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y libc6:i386 libstdc++6:i386 \
    && apt-get install -y zlib1g:i386 \
    && apt-get install -y locales \
    git-core build-essential bc \
    libssl-dev libncurses5-dev unzip gawk zlib1g-dev \
    subversion curl wget file python gettext \
    libxml-parser-perl zip kmod cpio sudo bash-completion \
    vim-common time device-tree-compiler libarchive-zip-perl \
    && apt-get clean
RUN locale-gen en_US.UTF-8
RUN useradd -m -k /etc/skel -u 1000 -G sudo -d /home/sdkuser sdkuser 
RUN echo "sdkuser ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/no_password
ENV FORCE_UNSAFE_CONFIGURE=1

# How to Use 
# build a docker image by dockerfile-realtek
#     sudo docker build -f dockerfile-realtek -t openwrt .
# run a container which is generated by above docker image
#     sudo docker run -ld --name openwrt --user sdkuser -v $(pwd)/build_script:/home/sdkuser/SDKRelease -v $OPENWRT_DL_PATH:/home/sdkuser/SDKRelease/src-downloads -it openwrt:latest bash
# .dockerignore
#     echo "./SDKRelease" > .dockerignore
